/**
 * Vendor-aware planning catalog. Products are dimensioned planning models that
 * link to the retailer's current search, not claims about live stock or price.
 * monetized stays false until a real affiliate network/tag exists.
 */

function vendorFor(row) {
  const group = String(row.group || row.category || "").toLowerCase();
  const query = encodeURIComponent(row.name || group || "furniture");
  if (/^(tv|speaker|gaming)$/.test(group)) {
    return { store: "Best Buy", vendor: "best-buy", productUrl: `https://www.bestbuy.com/site/searchpage.jsp?st=${query}` };
  }
  if (/^(sofa|sectional|table|rug|shelves)$/.test(group)) {
    return { store: "IKEA", vendor: "ikea", productUrl: `https://www.ikea.com/us/en/search/?q=${query}` };
  }
  if (group === "plant") {
    return { store: "The Home Depot", vendor: "home-depot", productUrl: `https://www.homedepot.com/s/${query}` };
  }
  return { store: "Wayfair", vendor: "wayfair", productUrl: `https://www.wayfair.com/keyword.php?keyword=${query}` };
}

function product(row) {
  const vendor = vendorFor(row);
  return {
    vendor: vendor.vendor,
    source: "retailer-planning",
    store: row.store || vendor.store,
    retailer: row.store || vendor.store,
    brand: row.brand || "Planning model",
    productUrl: row.productUrl || vendor.productUrl,
    affiliateUrl: row.affiliateUrl || "",
    affiliateNetwork: null,
    monetized: false,
    availability: "check_retailer",
    priceIsEstimate: true,
    modelSource: "procedural",
    glbUrl: "",
    ...row,
  };
}

export const CATALOG_TREE = [
  {
    id: "living",
    label: "Living Room",
    groups: [
      { id: "sofa", label: "Sofas" },
      { id: "sectional", label: "Sectionals" },
      { id: "chair", label: "Chairs" },
      { id: "table", label: "Tables" },
      { id: "rug", label: "Rugs" },
      { id: "lamp", label: "Lamps" },
    ],
  },
  {
    id: "entertainment",
    label: "Entertainment",
    groups: [
      { id: "tv", label: "TVs" },
      { id: "tv-stand", label: "TV stands" },
      { id: "speaker", label: "Speakers" },
      { id: "gaming", label: "Gaming setups" },
    ],
  },
  {
    id: "decor",
    label: "Decor",
    groups: [
      { id: "plant", label: "Plants" },
      { id: "art", label: "Art" },
      { id: "shelves", label: "Shelves" },
      { id: "mirror", label: "Mirrors" },
    ],
  },
];

export const SAMPLE_PRODUCTS = [
  product({
    id: "sr-sectional-gray",
    sku: "SR-SEC-GRAY",
    modelId: "sectional-gray",
    category: "sofa",
    group: "sectional",
    meshStyle: "sectional",
    name: "Modern Gray Sectional",
    brand: "Haven & Oak",
    price: 1299,
    widthIn: 112,
    heightIn: 34,
    depthIn: 64,
    swatch: "#6d737c",
    snap: "floor",
  }),
  product({
    id: "sr-sofa-charcoal",
    sku: "SR-SOFA-CHAR",
    modelId: "sofa-charcoal",
    category: "sofa",
    group: "sofa",
    meshStyle: "sofa",
    name: "Charcoal 3-Seat Sofa",
    brand: "Haven & Oak",
    price: 899,
    widthIn: 84,
    heightIn: 34,
    depthIn: 36,
    swatch: "#3d4248",
    snap: "floor",
  }),
  product({
    id: "sr-sofa-linen",
    sku: "SR-SOFA-LINEN",
    modelId: "sofa-linen",
    category: "sofa",
    group: "sofa",
    meshStyle: "sofa",
    name: "Sand Linen Sofa",
    brand: "Haven & Oak",
    price: 1099,
    widthIn: 86,
    heightIn: 33,
    depthIn: 38,
    swatch: "#cbb79a",
    snap: "floor",
  }),
  product({
    id: "sr-chair-lounge",
    sku: "SR-CHAIR-LOUNGE",
    modelId: "chair-lounge",
    category: "chair",
    group: "chair",
    meshStyle: "lounge",
    name: "Walnut Lounge Chair",
    brand: "Arbor",
    price: 349,
    widthIn: 32,
    heightIn: 34,
    depthIn: 34,
    swatch: "#6b4a32",
    snap: "floor",
  }),
  product({
    id: "sr-chair-accent",
    sku: "SR-CHAIR-ACCENT",
    modelId: "chair-accent",
    category: "chair",
    group: "chair",
    meshStyle: "chair",
    name: "Cream Accent Chair",
    brand: "Arbor",
    price: 279,
    widthIn: 30,
    heightIn: 32,
    depthIn: 32,
    swatch: "#e6dcc8",
    snap: "floor",
  }),
  product({
    id: "sr-table-coffee-oak",
    sku: "SR-TABLE-COFFEE",
    modelId: "coffee-oak",
    category: "table",
    group: "table",
    meshStyle: "coffee-table",
    name: "Oak Coffee Table",
    brand: "Arbor",
    price: 329,
    widthIn: 48,
    heightIn: 17,
    depthIn: 26,
    swatch: "#8b6a45",
    snap: "floor",
  }),
  product({
    id: "sr-table-coffee-marble",
    sku: "SR-TABLE-MARBLE",
    modelId: "coffee-marble",
    category: "table",
    group: "table",
    meshStyle: "coffee-table",
    name: "Marble Coffee Table",
    brand: "Lumen Home",
    price: 459,
    widthIn: 42,
    heightIn: 16,
    depthIn: 42,
    swatch: "#d8d4cc",
    accent: "marble",
    snap: "floor",
  }),
  product({
    id: "sr-table-side-oak",
    sku: "SR-SIDE-OAK",
    modelId: "side-oak",
    category: "table",
    group: "table",
    meshStyle: "side-table",
    name: "Oak Side Table",
    brand: "Arbor",
    price: 149,
    widthIn: 20,
    heightIn: 22,
    depthIn: 20,
    swatch: "#8b6a45",
    snap: "floor",
  }),
  product({
    id: "sr-table-side-walnut",
    sku: "SR-SIDE-WALNUT",
    modelId: "side-walnut",
    category: "table",
    group: "table",
    meshStyle: "side-table",
    name: "Walnut Side Table",
    brand: "Arbor",
    price: 129,
    widthIn: 18,
    heightIn: 24,
    depthIn: 18,
    swatch: "#4a3426",
    snap: "floor",
  }),
  product({
    id: "sr-rug-wool",
    sku: "SR-RUG-WOOL",
    modelId: "rug-wool",
    category: "rug",
    group: "rug",
    meshStyle: "rug",
    name: "Wool Area Rug 8×10",
    brand: "Field & Loom",
    price: 240,
    widthIn: 96,
    heightIn: 0.6,
    depthIn: 120,
    swatch: "#c4b49a",
    snap: "floor",
    collide: false,
  }),
  product({
    id: "sr-rug-terracotta",
    sku: "SR-RUG-TERRA",
    modelId: "rug-terra",
    category: "rug",
    group: "rug",
    meshStyle: "rug",
    name: "Terracotta Kilim Rug",
    brand: "Field & Loom",
    price: 380,
    widthIn: 96,
    heightIn: 0.6,
    depthIn: 108,
    swatch: "#a45a3c",
    snap: "floor",
    collide: false,
  }),
  product({
    id: "sr-lamp-brass",
    sku: "SR-LAMP-BRASS",
    modelId: "lamp-brass",
    category: "lamp",
    group: "lamp",
    meshStyle: "floor-lamp",
    name: "Brass Floor Lamp",
    brand: "Lumen Home",
    price: 90,
    widthIn: 14,
    heightIn: 62,
    depthIn: 14,
    swatch: "#c9a56a",
    snap: "floor",
  }),
  product({
    id: "sr-lamp-linen",
    sku: "SR-LAMP-LINEN",
    modelId: "lamp-linen",
    category: "lamp",
    group: "lamp",
    meshStyle: "floor-lamp",
    name: "Linen Floor Lamp",
    brand: "Lumen Home",
    price: 129,
    widthIn: 16,
    heightIn: 64,
    depthIn: 16,
    swatch: "#e8e2d0",
    snap: "floor",
  }),
  product({
    id: "sr-lamp-table",
    sku: "SR-LAMP-TABLE",
    modelId: "lamp-table",
    category: "lamp",
    group: "lamp",
    meshStyle: "table-lamp",
    name: "Ceramic Table Lamp",
    brand: "Lumen Home",
    price: 79,
    widthIn: 12,
    heightIn: 22,
    depthIn: 12,
    swatch: "#efe7d8",
    snap: "floor",
    sitOnHeightM: 0.56,
  }),
  product({
    id: "sr-tv-65",
    sku: "SR-TV-65",
    modelId: "tv-65",
    category: "tv",
    group: "tv",
    meshStyle: "tv",
    name: '65" 4K Smart TV',
    brand: "Vista",
    price: 749,
    widthIn: 57.1,
    heightIn: 32.7,
    depthIn: 2.8,
    swatch: "#1a1a1c",
    snap: "floor",
    sitOnHeightM: 0.5,
    wallAffinity: true,
  }),
  product({
    id: "sr-tv-75",
    sku: "SR-TV-75",
    modelId: "tv-75",
    category: "tv",
    group: "tv",
    meshStyle: "tv",
    name: '75" 4K Smart TV',
    brand: "Vista",
    price: 1099,
    widthIn: 65.9,
    heightIn: 37.8,
    depthIn: 2.9,
    swatch: "#111113",
    snap: "floor",
    sitOnHeightM: 0.5,
    wallAffinity: true,
  }),
  product({
    id: "sr-tv-55",
    sku: "SR-TV-55",
    modelId: "tv-55",
    category: "tv",
    group: "tv",
    meshStyle: "tv",
    name: '55" 4K Smart TV',
    brand: "Vista",
    price: 449,
    widthIn: 48.4,
    heightIn: 28,
    depthIn: 2.6,
    swatch: "#1a1a1c",
    snap: "floor",
    sitOnHeightM: 0.5,
    wallAffinity: true,
  }),
  product({
    id: "sr-stand-walnut",
    sku: "SR-STAND-WALNUT",
    modelId: "tv-stand-walnut",
    category: "cabinet",
    group: "tv-stand",
    meshStyle: "tv-stand",
    name: "Walnut TV Stand",
    brand: "Arbor",
    price: 499,
    widthIn: 70,
    heightIn: 20,
    depthIn: 18,
    swatch: "#4a3426",
    snap: "floor",
    wallAffinity: true,
  }),
  product({
    id: "sr-stand-media",
    sku: "SR-STAND-MEDIA",
    modelId: "media-console",
    category: "cabinet",
    group: "tv-stand",
    meshStyle: "tv-stand",
    name: "White Media Console",
    brand: "Haven & Oak",
    price: 399,
    widthIn: 64,
    heightIn: 18,
    depthIn: 16,
    swatch: "#ece8e0",
    snap: "floor",
    wallAffinity: true,
  }),
  product({
    id: "sr-speaker-tower",
    sku: "SR-SPEAK-TOWER",
    modelId: "speaker-tower",
    category: "decor",
    group: "speaker",
    meshStyle: "speaker",
    name: "Tower Speakers",
    brand: "Vista",
    price: 349,
    widthIn: 10,
    heightIn: 38,
    depthIn: 12,
    swatch: "#2a2a2c",
    snap: "floor",
    wallAffinity: true,
  }),
  product({
    id: "sr-soundbar",
    sku: "SR-SOUNDBAR",
    modelId: "soundbar",
    category: "decor",
    group: "speaker",
    meshStyle: "soundbar",
    name: "Dolby Soundbar",
    brand: "Vista",
    price: 199,
    widthIn: 38,
    heightIn: 2.4,
    depthIn: 4,
    swatch: "#1c1c1e",
    snap: "floor",
    sitOnHeightM: 0.52,
    wallAffinity: true,
  }),
  product({
    id: "sr-game-chair",
    sku: "SR-GAME-CHAIR",
    modelId: "gaming-chair",
    category: "chair",
    group: "gaming",
    meshStyle: "gaming-chair",
    name: "Racing Gaming Chair",
    brand: "Pulse",
    price: 229,
    widthIn: 28,
    heightIn: 48,
    depthIn: 28,
    swatch: "#1a1a1c",
    accent: "#c0392b",
    snap: "floor",
  }),
  product({
    id: "sr-game-desk",
    sku: "SR-GAME-DESK",
    modelId: "gaming-desk",
    category: "desk",
    group: "gaming",
    meshStyle: "desk",
    name: "RGB Gaming Desk",
    brand: "Pulse",
    price: 279,
    widthIn: 55,
    heightIn: 30,
    depthIn: 24,
    swatch: "#1c1c20",
    snap: "floor",
    wallAffinity: true,
  }),
  product({
    id: "sr-game-monitor",
    sku: "SR-GAME-MON",
    modelId: "monitor",
    category: "tv",
    group: "gaming",
    meshStyle: "monitor",
    name: '34" Ultrawide Monitor',
    brand: "Pulse",
    price: 399,
    widthIn: 32,
    heightIn: 16,
    depthIn: 8,
    swatch: "#111113",
    snap: "floor",
    sitOnHeightM: 0.76,
  }),
  product({
    id: "sr-plant-fig",
    sku: "SR-PLANT-FIG",
    modelId: "plant-fig",
    category: "decor",
    group: "plant",
    meshStyle: "plant-fig",
    name: "Fiddle Leaf Fig",
    brand: "Grove",
    price: 89,
    widthIn: 22,
    heightIn: 62,
    depthIn: 22,
    swatch: "#2f6b3a",
    snap: "floor",
  }),
  product({
    id: "sr-plant-olive",
    sku: "SR-PLANT-OLIVE",
    modelId: "plant-olive",
    category: "decor",
    group: "plant",
    meshStyle: "plant-olive",
    name: "Potted Olive Tree",
    brand: "Grove",
    price: 129,
    widthIn: 24,
    heightIn: 68,
    depthIn: 24,
    swatch: "#6b8f3a",
    snap: "floor",
  }),
  product({
    id: "sr-plant-snake",
    sku: "SR-PLANT-SNAKE",
    modelId: "plant-snake",
    category: "decor",
    group: "plant",
    meshStyle: "plant-snake",
    name: "Snake Plant",
    brand: "Grove",
    price: 45,
    widthIn: 12,
    heightIn: 28,
    depthIn: 12,
    swatch: "#3d7a48",
    snap: "floor",
  }),
  product({
    id: "sr-art-abstract",
    sku: "SR-ART-ABS",
    modelId: "art-abstract",
    category: "decor",
    group: "art",
    meshStyle: "art",
    name: "Abstract Canvas",
    brand: "Atelier",
    price: 180,
    widthIn: 40,
    heightIn: 30,
    depthIn: 1.5,
    swatch: "#7a5a44",
    snap: "wall",
    wallMounted: true,
    mountHeightM: 1.55,
  }),
  product({
    id: "sr-art-landscape",
    sku: "SR-ART-LAND",
    modelId: "art-landscape",
    category: "decor",
    group: "art",
    meshStyle: "art",
    name: "Landscape Print",
    brand: "Atelier",
    price: 120,
    widthIn: 36,
    heightIn: 24,
    depthIn: 1.2,
    swatch: "#4a6a78",
    snap: "wall",
    wallMounted: true,
    mountHeightM: 1.5,
  }),
  product({
    id: "sr-art-gallery",
    sku: "SR-ART-GAL",
    modelId: "art-gallery",
    category: "decor",
    group: "art",
    meshStyle: "art-set",
    name: "Gallery Frame Set",
    brand: "Atelier",
    price: 160,
    widthIn: 48,
    heightIn: 28,
    depthIn: 1.2,
    swatch: "#d8cfc0",
    snap: "wall",
    wallMounted: true,
    mountHeightM: 1.5,
  }),
  product({
    id: "sr-shelf-book",
    sku: "SR-SHELF-BOOK",
    modelId: "bookshelf",
    category: "shelves",
    group: "shelves",
    meshStyle: "bookshelf",
    name: "Oak Bookshelf",
    brand: "Arbor",
    price: 249,
    widthIn: 36,
    heightIn: 72,
    depthIn: 12,
    swatch: "#8b6a45",
    snap: "floor",
    wallAffinity: true,
  }),
  product({
    id: "sr-shelf-float",
    sku: "SR-SHELF-FLOAT",
    modelId: "float-shelf",
    category: "shelves",
    group: "shelves",
    meshStyle: "float-shelf",
    name: "Floating Shelves",
    brand: "Arbor",
    price: 89,
    widthIn: 36,
    heightIn: 24,
    depthIn: 8,
    swatch: "#4a3426",
    snap: "wall",
    wallMounted: true,
    mountHeightM: 1.45,
  }),
  product({
    id: "sr-mirror-round",
    sku: "SR-MIRROR-ROUND",
    modelId: "mirror-round",
    category: "decor",
    group: "mirror",
    meshStyle: "mirror-round",
    name: "Round Wall Mirror",
    brand: "Lumen Home",
    price: 159,
    widthIn: 28,
    heightIn: 28,
    depthIn: 1.5,
    swatch: "#c9a56a",
    snap: "wall",
    wallMounted: true,
    mountHeightM: 1.55,
  }),
  product({
    id: "sr-mirror-leaner",
    sku: "SR-MIRROR-LEAN",
    modelId: "mirror-leaner",
    category: "decor",
    group: "mirror",
    meshStyle: "mirror-leaner",
    name: "Floor Leaner Mirror",
    brand: "Lumen Home",
    price: 219,
    widthIn: 24,
    heightIn: 66,
    depthIn: 4,
    swatch: "#d8d4cc",
    snap: "floor",
    wallAffinity: true,
  }),
];

export const PRODUCT_BY_ID = Object.fromEntries(SAMPLE_PRODUCTS.map((p) => [p.id, p]));

export const VENDOR_OPTIONS = [
  { id: "all", label: "All vendors" },
  { id: "best-buy", label: "Best Buy" },
  { id: "ikea", label: "IKEA" },
  { id: "wayfair", label: "Wayfair" },
  { id: "home-depot", label: "Home Depot" },
];

/** Professionally staged living room. Coordinates in meters, origin at room center. */
export const DEFAULT_LAYOUT = [
  { id: "sr-rug-wool", x: 0.15, z: 0.35, rot: 0 },
  { id: "sr-stand-walnut", x: 0, z: -2.28, rot: 0 },
  { id: "sr-tv-65", x: 0, z: -2.18, rot: 0, y: 0.52 },
  { id: "sr-sectional-gray", x: 0.55, z: 1.35, rot: Math.PI },
  { id: "sr-table-coffee-oak", x: 0.05, z: 0.28, rot: 0 },
  { id: "sr-chair-lounge", x: -2.05, z: 0.15, rot: Math.PI / 2 },
  { id: "sr-chair-accent", x: 2.15, z: 0.05, rot: -Math.PI / 2 },
  { id: "sr-table-side-oak", x: -1.35, z: 1.45, rot: 0 },
  { id: "sr-table-side-walnut", x: 2.05, z: 1.35, rot: 0 },
  { id: "sr-lamp-brass", x: -1.85, z: 1.85, rot: 0 },
  { id: "sr-lamp-brass", x: 2.25, z: 1.75, rot: 0 },
  { id: "sr-lamp-table", x: -1.35, z: 1.45, rot: 0, y: 0.58 },
  { id: "sr-plant-fig", x: -2.7, z: -1.95, rot: 0.3 },
  { id: "sr-plant-olive", x: 2.7, z: -1.9, rot: -0.2 },
  { id: "sr-plant-snake", x: 2.55, z: 1.95, rot: 0 },
  { id: "sr-art-abstract", x: 3.14, z: 1.2, rot: -Math.PI / 2, y: 1.55 },
  { id: "sr-mirror-round", x: 3.14, z: 0.2, rot: -Math.PI / 2, y: 1.55 },
  { id: "sr-speaker-tower", x: -1.15, z: -2.22, rot: 0 },
  { id: "sr-speaker-tower", x: 1.15, z: -2.22, rot: 0 },
];

export function money(n) {
  return Number(n || 0).toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
}

export function productsInGroup(groupId, vendorId = "all") {
  return SAMPLE_PRODUCTS.filter((p) => p.group === groupId && (vendorId === "all" || p.vendor === vendorId));
}

export function findProduct(id) {
  return PRODUCT_BY_ID[id] || SAMPLE_PRODUCTS.find((p) => p.sku === id || p.modelId === id) || null;
}

/** Map a vendor-API product onto a mesh style so listing-3d still renders furniture. */
export function normalizeProduct(raw = {}) {
  if (!raw || typeof raw !== "object") return null;
  const known = findProduct(raw.id) || findProduct(raw.sku) || findProduct(raw.modelId);
  const category = String(raw.category || known?.category || "decor").toLowerCase();
  const groupGuess =
    raw.group ||
    known?.group ||
    (category === "sofa" && /section/i.test(raw.name || "") ? "sectional" : category === "cabinet" ? "tv-stand" : category);
  return {
    ...(known || {}),
    ...raw,
    category,
    group: groupGuess,
    meshStyle: raw.meshStyle || known?.meshStyle || meshStyleFor(category, raw.name),
    store: raw.store || raw.retailer || raw.vendor || "Catalog",
    retailer: raw.retailer || raw.store || raw.vendor || "Catalog",
    monetized: !!raw.monetized,
    widthIn: Number(raw.widthIn || known?.widthIn) || 24,
    heightIn: Number(raw.heightIn || known?.heightIn) || 24,
    depthIn: Number(raw.depthIn || known?.depthIn) || 24,
    snap: raw.snap || known?.snap || (category === "art" ? "wall" : "floor"),
    wallMounted: !!(raw.wallMounted || known?.wallMounted),
  };
}

function meshStyleFor(category, name = "") {
  const n = name.toLowerCase();
  if (category === "sofa" && n.includes("section")) return "sectional";
  if (category === "sofa") return "sofa";
  if (category === "chair" && n.includes("game")) return "gaming-chair";
  if (category === "chair") return "chair";
  if (category === "table" && n.includes("coffee")) return "coffee-table";
  if (category === "table") return "side-table";
  if (category === "desk") return "desk";
  if (category === "tv") return n.includes("monitor") ? "monitor" : "tv";
  if (category === "lamp") return n.includes("table") ? "table-lamp" : "floor-lamp";
  if (category === "rug") return "rug";
  if (category === "cabinet") return "tv-stand";
  if (category === "shelves") return "bookshelf";
  if (category === "decor" && n.includes("plant")) return "plant-fig";
  if (category === "decor" && n.includes("mirror")) return "mirror-round";
  if (category === "decor" && (n.includes("art") || n.includes("canvas") || n.includes("print"))) return "art";
  if (category === "decor" && n.includes("speak")) return "speaker";
  return "box";
}
