"use strict";

const { LISTING_STATUS } = require("../constants");

/**
 * Fictional sample listings, shaped exactly like a mapped RESO record so the
 * API contract doesn't change when LISTINGS_MODE flips from mock to provider.
 */
const SAMPLE_LISTINGS = [
  {
    id: "mock-001",
    mlsNumber: "MOCK-0001",
    title: "412 Palm Crest Drive",
    location: "Summerlin, Las Vegas, NV",
    image: "images/mansion-1.jpg",
    images: ["images/mansion-1.jpg", "images/gallery/g-01.jpg"],
    beds: 6,
    baths: 7,
    sqft: 9800,
    listPrice: 8900000,
    status: LISTING_STATUS.ACTIVE,
    propertyType: "Residential",
    desc: "Sample listing for local development. Not a real property.",
    listingOffice: "Smart Realty Sample Office",
    listingAgent: "Sample Agent",
    mlsSourceName: "SAMPLE-MLS",
    asOf: "2026-08-18T12:00:00Z",
    listingDate: "2026-08-18T12:00:00Z",
    city: "Las Vegas",
    state: "NV",
    postalCode: "89135",
    address: "412 Palm Crest Drive",
    latitude: 36.1699,
    longitude: -115.3272,
    sourceUrl: "",
    lastUpdated: "2026-08-18T12:00:00Z",
    source: "mock",
  },
  {
    id: "mock-002",
    mlsNumber: "MOCK-0002",
    title: "88 Horizon Ridge Way",
    location: "Henderson Hills, NV",
    image: "images/mansion-2.jpg",
    images: ["images/mansion-2.jpg", "images/gallery/g-02.jpg"],
    beds: 8,
    baths: 10,
    sqft: 14200,
    listPrice: 14500000,
    status: LISTING_STATUS.PENDING,
    propertyType: "Residential",
    desc: "Sample listing for local development. Not a real property.",
    listingOffice: "Smart Realty Sample Office",
    listingAgent: "Sample Agent",
    mlsSourceName: "SAMPLE-MLS",
    asOf: "2026-08-10T12:00:00Z",
    listingDate: "2026-08-10T12:00:00Z",
    city: "Henderson",
    state: "NV",
    postalCode: "89052",
    address: "88 Horizon Ridge Way",
    source: "mock",
  },
  {
    id: "mock-003",
    mlsNumber: "MOCK-0003",
    title: "1900 Mediterranean Hillside Ct",
    location: "Beverly Hills Adjacent, CA",
    image: "images/mansion-3.jpg",
    images: ["images/mansion-3.jpg", "images/gallery/g-03.jpg"],
    beds: 7,
    baths: 8,
    sqft: 11200,
    listPrice: 16800000,
    status: LISTING_STATUS.SOLD,
    propertyType: "Residential",
    desc: "Sample listing for local development. Not a real property.",
    listingOffice: "Smart Realty Sample Office",
    listingAgent: "Sample Agent",
    mlsSourceName: "SAMPLE-MLS",
    asOf: "2026-07-01T12:00:00Z",
    listingDate: "2026-07-01T12:00:00Z",
    city: "Beverly Hills",
    state: "CA",
    address: "1900 Mediterranean Hillside Ct",
    source: "mock",
  },
  {
    id: "mock-004",
    mlsNumber: "MOCK-0004",
    title: "918 Baxter Avenue",
    location: "Louisville, KY 40204",
    image: "images/listing-19.jpg",
    images: ["images/listing-19.jpg", "images/gallery/g-09.jpg", "images/gallery/g-10.jpg", "images/gallery/g-11.jpg"],
    beds: 3,
    baths: 2,
    sqft: 1840,
    lotSize: 4356,
    listPrice: 329000,
    status: LISTING_STATUS.ACTIVE,
    propertyType: "Residential",
    desc: "Sample Louisville listing for 3D room preview. Not a live MLS listing.",
    listingOffice: "Smart Realty Sample Office",
    listingAgent: "Sample Agent",
    mlsSourceName: "SAMPLE-MLS",
    asOf: "2026-08-19T15:00:00Z",
    listingDate: "2026-08-19T15:00:00Z",
    city: "Louisville",
    state: "KY",
    postalCode: "40204",
    address: "918 Baxter Avenue",
    latitude: 38.237,
    longitude: -85.726,
    lastUpdated: "2026-08-19T15:00:00Z",
    source: "mock",
  },
];

function createMockListingsProvider() {
  return {
    name: "mock",
    sandbox: true,
    configured: true,
    async fetchListings() {
      return { listings: SAMPLE_LISTINGS, complete: true, incremental: false, syncedAt: new Date().toISOString() };
    },
  };
}

module.exports = { createMockListingsProvider, SAMPLE_LISTINGS };
